### ISSUE TITLE
50% of the links in the documentation seem to be broken

### ISSUE THREAD

**Issue by AlexanderFabisch** [envire/envire.github.io#1]
For example
* http://envire.github.io/docs/graph_example_transforms.html
* http://envire.github.io/docs/graph_example_add_frame.html
* http://envire.github.io/docs/maps_types_tological.html
* http://envire.github.io/docs/maps_integration.html
* http://envire.github.io/docs/simulation_robot_representation.html
* http://envire.github.io/docs/collsion_overview.html

**Comment by annaborn** [comment]
Thank you for info! No pages means: no information was written for certain topic. I added empty pages, so it is now clear, that there is lake of documentation at the moment.

**Comment by AlexanderFabisch** [comment]
Thanks!
